baseurl = "https://ryliet.netlify.app/"
title = "Rylie"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
# enableEmoji = true

# disqusShortname = "yourdiscussshortname"

[params]
    author = "Rylie T"
    description = "Cool Dog Guy's Personal Website"
    keywords = "IT student, developer, student"
    info = "Penultimate IT student"
    avatarurl = "images/polarbear.jpg"
    #gravatar = "john.doe@example.com"
    footercontent = "Hello~"

    dateformat = "2 January, 2006"

    hideCredits = false
    hideCopyright = false
    since = 2021

    # Git Commit in Footer, uncomment the line below to enable it.
    commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "auto"

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = []

    # Custom JS
    custom_js = []

# If you want to use fathom(https://usefathom.com) for analytics, add this section
[params.fathomAnalytics]
    siteID = "ABCDE"
    # Default value is cdn.usefathom.com, overwrite this if you are self-hosting
    serverURL = "analytics.example.com"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "Email"
    icon = "fas fa-envelope"
    weight = 1
    url = "ryleetsang@gmail.com" 

[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin-in"
    weight = 2
    url = "https://www.linkedin.com/in/ryliet/"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 3
    url = "https://github.com/Rrrrly"



[languages]
    [languages.en]
        languagename = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "Home"
            weight = 1
            url = "#"

            [[languages.en.menu.main]]
            name = "About"
            weight = 2
            url = "about/"

            [[languages.en.menu.main]]
            name = "Blog"
            weight = 3
            url = "posts/"

            [[languages.en.menu.main]]
            name = "Experience"
            weight = 4
            url = "experience/"
